#+TITLE: PHIL160
#+STARTUP: indent

* Lecture notes
** Like last lecture
*** The Consent Argument - _unsound_
P1: If a women has consensual sex, she consents to carry the fetus to term if she gets pregnant
P2: If a woman consents to carry a getus to term, she's obligated to do so
----------------
C: If a woman has a consensual sex, she's obligated to carry the fetus to term if she gets pregnent
*Note* Focusing on informed, competent consent
*Note* In important cases, you want explicit consent

Different forms of consent:
_Explicit Consent_: Agree and State Agreement
_Implicit Consent_: Agree and dont state (Would agree of explicitly asked)
_Implied Consent_: Behaving in ways that according to well known socal norms that suggest agreement

*EX*: Tips at restraunt
Explicit: He tells the waiter that this is the tip and this is for the meal
Implicit: He just leaves the money on the table with the tip and money for the meal
Implied: He leaves a wad of cash and forgets it in the restraunt, some of it is not for the meal or tips

*EX*: 
| Consent  | P1 | P2 |
| Explicit | F  |    |
| Implicit | F  |    |
| Implied  | ?  | F  |

*EX*: Slave if you're wearing pants and someone touches you
If they touch you are you obligated to be their slave

*** The Negligence Argument
P1: If a woman gets pregnent due to consensual sex she's, at least partially, causally responsible for the fetus being dependent on her
P2: To the extent to which you're causally responsible for someone being dependent on you, you're morally responsible for helping them
-------------
C: If a woman gets pregnent due to consensual sex, she's, at least partially, morally responsible for helping the fetus

*EX*: Drowning - If you are untrained
Case 1: Just arrived and sees someone who is drowning - Obligated to save them?
Case 2: You tell the person that there are no riptides and then there are riptides - Obligated to save them?
Case 3: You figure out they can't swim and then push them in the water - Obligated to save them?

When are you morally obligated to keep the fetus?

| Feinberg                              | Obligated? |
| Rape                                  | No         |
| Consensual Sex w/ Protection (defect) | No         |
| Consensual Sex and Protection         | ?          |
| Consensial Sex and No Protection      | Yes        |
| Consensual Sex and Intent             | Yes        |

*Boonin*: "P1 is ok, P2 is false"
*EX*: Violinist and Dr. Discovery

Fix: Replace "dependent on you" to "worse off" in *The Negligence Argument*

P1: If a woman gets pregnent due to consensual sex she's, at least partially, causally responsible for the fetus being _worse off_
P2: To the extent to which you're causally responsible for someone being _worse off_, you're morally responsible for helping them
-------------
C: If a woman gets pregnent due to consensual sex, she's, at least partially, morally responsible for helping the fetus

*Key Question*: Is a fetus worse off then it would be if it hadn't existed?
P1: True
P2: False
